
name: Deploy Laravel to Azure

on:
  push:
    branches: [ main ]
    paths:
      - "backend-project/**"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: backend-project
        run: |
          composer install --no-dev --optimize-autoloader
          cp .env.example .env || true
          php artisan key:generate --force

      - name: Create ZIP for deploy
        run: |
          cd backend-project
          zip -r ../backend.zip .

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: backend-toni-php
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: backend.zip
